### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by TrimeGeld** [digiassetX/digisweep#4]
I need Help with digisweep, I don't know how to get my money from Digibyte Go.....
please, I need Help

**Comment by wfurnival** [comment]
Greetings,

May I start by saying thank you for your sweeping service, it has helped solve a big problem for me.

However, it has created an even bigger on that should be easy to solve.

I was using the mctriva sweep service and the vast majority of my funds got sent to the donation address somehow.

While I dont mind making a donation, this is a catastrophic loss due to the amount.

100081.66903601 DGB were sent to the donation address without my consent. Perhaps I made an error, but the last sweeps I did, didnt have this problem.

Transaction #
5aefb68e61269b01bb833e10dae1c4221efc31ed254927ebc5242d98f172733d

Link:
https://digibyteblockexplorer.com/address/D9RVKBjzRvnzUUTHxZBNZ3kfAHrmci1v76

Would you please kindly refund me 99081.66903601 DGB to address:
dgb1qr6c2jl47pnguvuaf20kku20p5vvs40skkx079p

I would be happy to leave 1000 DGB as a donation.

Thank you kindly for your help and consideration..

Kind regards

WF

**Comment by TrimeGeld** [comment]
fertig
